Repository wporter/air-quality, pull requests merged in 2023-10, with the labels that each got.

#2 Setup README
  README.md
Labels: Ready to Merge

#10 Deployment
  Dockerfile
  cloudbuild.yaml
  package-lock.json
  package.json
Labels: Ready to Review

#15 added cypress framework
  .github/workflows/pull-request.yaml
  cypress.config.js
  cypress/component/Example.cy.js
  cypress/e2e/home.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/component-index.html
  cypress/support/component.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: Testing

#13 authentication handler completed
  src/app/utils/authenticate.js
Labels: Ready to Review, Backend
