Repository wporter/air-quality, pull requests merged in 2023-12, with the labels that each got.

#32 Map Component
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/components/Map.jsx
Labels: Ready to Review

#34 Landing page component finished!
  package-lock.json
  package.json
  public/landingWaves.svg
  src/app/layout.js
  src/app/page.js
  src/components/Welcome.jsx
  tailwind.config.js
Labels: Ready to Review, Ready to Merge, Frontend

#37 Add Custom Marker
  src/components/Map.jsx
  src/components/Marker.jsx
Labels: Ready to Review

#39 Landing Fixes
  src/app/page.js
  src/components/Welcome.jsx
Labels: Ready to Review

#40 Update CI
  .github/workflows/pull-request.yaml
  cypress.config.js
  package-lock.json
  package.json
Labels: Repository, Ready to Review

#41 Populate Map with Locations
  package-lock.json
  package.json
  src/app/api/locations/route.js
  src/app/page.js
  src/app/utils/api.js
  src/components/Map.jsx
  src/components/Marker.jsx
Labels: Ready to Review, Backend, Frontend

#42 Edits to public view section of landing page.
  public/next.svg
  public/svg/landingWaves.svg
  public/vercel.svg
  src/app/page.js
  src/components/Map.jsx
  src/components/Welcome.jsx
Labels: Ready to Review, Frontend

#54 Setup Research View
  src/app/api/locations/route.js
  src/app/layout.js
  src/app/page.js
  src/app/researcher/page.js
  src/components/researcher/Data.jsx
  src/components/researcher/Map.jsx
  src/components/researcher/Navigation.jsx
  src/components/researcher/Protected.jsx
  src/components/researcher/SideNavigation.jsx
  src/utils/api.js
  src/utils/authenticate.js
Labels: Ready to Review, Frontend

#58 Setup Map in Researcher Dashboard
  src/app/page.js
  src/components/Map.jsx
  src/components/researcher/Map.jsx
  src/components/researcher/Status.jsx
Labels: Ready to Review, Frontend

#65 Setup Researcher Members
  src/app/researcher/members/page.jsx
  src/app/researcher/page.js
  src/components/researcher/dashboard/Data.jsx
  src/components/researcher/dashboard/Map.jsx
  src/components/researcher/dashboard/Status.jsx
  src/components/researcher/members/Header.jsx
  src/components/researcher/members/Members.jsx
Labels: Ready to Review, Frontend

#66 Setup Data Table
  package-lock.json
  package.json
  src/components/researcher/Search.jsx
  src/components/researcher/dashboard/Data.jsx
  tailwind.config.js
Labels: Ready to Review, Frontend

#69 Status component styled
  src/components/researcher/dashboard/Map.jsx
  src/components/researcher/dashboard/Status.jsx
  tailwind.config.js
Labels: Ready to Review, Frontend
