Repository wporter/air-quality, pull requests merged in 2024-01, with the labels that each got.

#70 Researcher's side navigation bar done
  src/components/researcher/SideNavigation.jsx
  src/components/researcher/dashboard/Status.jsx
Labels: Ready to Review, Frontend

#71 Extended next and removed unnecessary react rules
  .eslintrc.json
  package-lock.json
  package.json
Labels: Repository

#72 Error handling pages completed
  public/svg/errorWaves.svg
  src/app/error.js
  src/app/not-found.js
  src/components/BackToHomeButton.jsx
  src/components/Error.jsx
  src/components/ErrorNavigation.jsx
Labels: Repository, Ready to Review, Frontend

#74 Fixed error page nav bar
  src/components/Error.jsx
  src/components/ErrorNavigation.jsx
  src/components/Welcome.jsx
Labels: Ready to Merge, Bug Fix, Frontend

#73 Updates styles of the nav
  src/components/Navigation.jsx
  src/components/researcher/dashboard/Data.jsx
  tailwind.config.js
Labels: Frontend

#78 added tag component and fixed styling
  src/app/page.js
  src/components/researcher/Tag.jsx
  tailwind.config.js
Labels: Frontend

#75 Added custom map markers
  src/components/BackToHomeButton.jsx
  src/components/Error.jsx
  src/components/Marker.jsx
  src/components/Navigation.jsx
Labels: Ready to Review, Frontend

#77 researcher nav bar
  src/app/page.js
  src/components/researcher/Navigation.jsx
Labels: Ready to Review, Frontend

#79 Added footer
  src/app/layout.js
  src/app/page.js
  src/components/Footer.jsx
Labels: Ready to Merge, Frontend

#76 Name header set up
  src/components/BackToHomeButton.jsx
  src/components/researcher/dashboard/Map.jsx
Labels: Ready to Merge, Frontend

#86 Touch ups on researcher's view page
  src/components/Footer.jsx
  src/components/Navigation.jsx
  src/components/researcher/Navigation.jsx
  src/components/researcher/Protected.jsx
  src/components/researcher/SideNavigation.jsx
  src/components/researcher/Tag.jsx
  src/components/researcher/dashboard/Data.jsx
  src/components/researcher/dashboard/Map.jsx
  tailwind.config.js
Labels: Ready to Review, Frontend

#88 Add Dropdown
  src/components/researcher/Search.jsx
  src/components/researcher/SideNavigation.jsx
  src/components/researcher/dashboard/Data.jsx
  src/components/researcher/dashboard/Dropdown.jsx
Labels: Frontend

#87 User profile picture completed.
  src/components/Footer.jsx
  src/components/researcher/Navigation.jsx
  src/components/researcher/SideNavigation.jsx
  src/components/researcher/dashboard/Map.jsx
  src/components/researcher/dashboard/Status.jsx
  tailwind.config.js
Labels: Ready to Review, Frontend

#92 About Page Skeleton
  src/app/about/page.js
  src/app/layout.js
  src/app/page.js
  src/components/BackToHomeButton.jsx
  src/components/Error.jsx
  src/components/Navigation.jsx
  src/components/about/About.jsx
  src/components/about/Profile.jsx
  src/data/Members.js
Labels: Ready to Merge
